# Generated by Django 3.2.8 on 2021-12-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_swabbed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(default=None, max_length=30)),
                ('swabSpot', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
