# Generated by Django 3.2.8 on 2021-10-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('alamat', models.TextField()),
                ('deskripsi', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
