# Generated by Django 3.2.8 on 2021-10-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='foto',
            field=models.ImageField(blank=True, default='static/image/default.jpg', upload_to='media/'),
        ),
    ]
