# Generated by Django 3.2.8 on 2021-10-27 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info_hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='nama',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='deskripsi',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='alamat',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='namaHotel',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
