# Generated by Django 3.2.7 on 2021-10-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_page', '0002_alter_artikel_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='deskripsi',
            field=models.CharField(max_length=20),
        ),
    ]
