# Generated by Django 3.2.7 on 2021-10-27 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_page', '0003_alter_artikel_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='time_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
