# Generated by Django 3.2.7 on 2021-10-27 16:53

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_page', '0005_artikel_penulis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='penulis',
            field=models.CharField(default=django.contrib.auth.models.AnonymousUser, max_length=30),
        ),
    ]
