# Generated by Django 3.2.7 on 2021-10-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_page', '0006_alter_artikel_penulis'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(default='static/image/default.jpg', upload_to=''),
        ),
    ]
