# Generated by Django 3.2.7 on 2021-10-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_page', '0007_artikel_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(default='static/image/default.jpg', upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='time_published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
