# Generated by Django 3.2.7 on 2021-10-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_page', '0010_alter_artikel_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='date_published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
