# Generated by Django 3.2.7 on 2021-10-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_page', '0011_alter_artikel_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
