# Generated by Django 3.2.8 on 2021-10-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_page', '0013_alter_artikel_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(default='static/image/default.jpg', upload_to='images/'),
        ),
    ]
