# Generated by Django 3.2.7 on 2021-10-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_page', '0017_auto_20211028_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='deskripsi',
            field=models.CharField(max_length=500),
        ),
    ]
