# Generated by Django 3.2.7 on 2021-10-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_page', '0018_alter_artikel_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='gambar',
            field=models.TextField(),
        ),
    ]
