# Generated by Django 3.2.8 on 2021-10-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_page', '0002_alter_hotel_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='review',
            new_name='detail',
        ),
    ]
