# Generated by Django 3.2.8 on 2021-10-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('deskripsi', models.TextField()),
                ('icon', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
