# Generated by Django 3.2.8 on 2021-10-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fitur_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitur',
            name='link',
            field=models.CharField(default='-', max_length=30),
            preserve_default=False,
        ),
    ]
