# Generated by Django 3.2.8 on 2021-10-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_covid', '0002_country_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code2',
            field=models.CharField(default='id', editable=False, max_length=2),
        ),
    ]
