# Generated by Django 3.2.8 on 2021-10-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_covid', '0003_country_code2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code2',
            field=models.CharField(editable=False, max_length=2),
        ),
    ]
