# Generated by Django 3.2.8 on 2021-10-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_to', models.CharField(max_length=1024)),
                ('negara_detail', models.CharField(max_length=1024)),
                ('support_dari', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('keluhan', models.TextField()),
                ('saran', models.TextField()),
            ],
        ),
    ]
