# Generated by Django 3.2.8 on 2021-11-04 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='negara_detail',
            new_name='Lokasi_kejadian',
        ),
        migrations.RenameField(
            model_name='support',
            old_name='support_dari',
            new_name='Negara_yang_dituju',
        ),
        migrations.RemoveField(
            model_name='support',
            name='support_to',
        ),
        migrations.RemoveField(
            model_name='support',
            name='title',
        ),
        migrations.AddField(
            model_name='support',
            name='Kejadian_secara_umum',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
