# Generated by Django 3.2.8 on 2021-11-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_page', '0002_auto_20211104_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='Kejadian_secara_umum',
            field=models.CharField(max_length=1024),
        ),
    ]
